function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(7)=1;
    ys_(8)=0;
    ys_(4)=1/params(1)-(1-params(2));
    ys_(1)=ys_(4)/params(6)*(1-params(3))/params(3)*(ys_(4)/params(3))^(1/(params(3)-1));
    ys_(5)=params(6)*ys_(1);
    ys_(3)=ys_(1)/((ys_(4)/params(3))^(params(3)/(params(3)-1))-params(2)*(ys_(4)/params(3))^(1/(params(3)-1)));
    ys_(2)=ys_(3)*ys_(5)*params(3)/(1-params(3))/ys_(4);
    ys_(6)=ys_(3)^(1-params(3))*ys_(2)^params(3);
    % Auxiliary equations
end
