function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(1)=0;
    ys_(3)=1/params(3)-1;
    ys_(4)=0;
    ys_(2)=0;
    ys_(5)=0;
    ys_(6)=0;
    % Auxiliary equations
end
