function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(8)=1;
    ys_(6)=0;
    ys_(1)=0;
    ys_(2)=params(2)+params(3);
    ys_(5)=1/(1/(1+params(1))*(1+ys_(1)))-1;
    ys_(3)=ys_(2)*(1+ys_(1))/(1+ys_(1)-1/(1+params(1)));
    ys_(4)=ys_(8)*ys_(2)/(1+ys_(1)-1/(1+params(1))*(1+ys_(6)));
    ys_(7)=params(3)*(1+ys_(1))/(ys_(5)-ys_(1));
    % Auxiliary equations
end
