function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(1)=1/(params(1)*params(5))^(1/(1+params(2)));
    ys_(3)=1/params(3)-1;
    ys_(4)=1/params(5);
    ys_(2)=1/(params(1)*params(5))^(1/(1+params(2)));
    ys_(5)=1/(params(1)*params(5))^(1/(1+params(2)));
    ys_(6)=0;
    % Auxiliary equations
end
